Repository alibaba/hooks, pull requests merged in 2020-08, with the labels that each got.

#563 feat: support multiple target on useClickAway
  packages/hooks/src/useClickAway/__tests__/index.test.ts
  packages/hooks/src/useClickAway/demo/demo3.tsx
  packages/hooks/src/useClickAway/index.en-US.md
  packages/hooks/src/useClickAway/index.ts
  packages/hooks/src/useClickAway/index.zh-CN.md
Labels: enhancement

#570 Feat/use timeout
  packages/hooks/src/index.ts
  packages/hooks/src/useTimeout/__tests__/index.test.ts
  packages/hooks/src/useTimeout/demo/demo1.tsx
  packages/hooks/src/useTimeout/index.en-US.md
  packages/hooks/src/useTimeout/index.ts
  packages/hooks/src/useTimeout/index.zh-CN.md
Labels: feature

#574 doc: add some tips about browser compatibilty
  docs/docs/faq.en-US.md
  docs/docs/faq.zh-CN.md
Labels: documentation

#569 Feat/use network
  packages/hooks/src/index.ts
  packages/hooks/src/useNetwork/__tests__/index.test.ts
  packages/hooks/src/useNetwork/demo/demo1.tsx
  packages/hooks/src/useNetwork/index.en-US.md
  packages/hooks/src/useNetwork/index.ts
  packages/hooks/src/useNetwork/index.zh-CN.md
Labels: feature

#446 feat: useUrlState
  .eslintrc.js
  .umirc.js
  README.md
  README.zh-CN.md
  gulpfile.js
  packages/use-request/README.md
  packages/use-request/src/index.ts
  packages/use-url-state/README.md
  packages/use-url-state/demo/demo1.tsx
  packages/use-url-state/demo/demo2.tsx
  packages/use-url-state/gulpfile.js
  packages/use-url-state/index.en-US.md
  packages/use-url-state/index.zh-CN.md
  packages/use-url-state/package.json
  packages/use-url-state/src/__tests__/browser.test.tsx
  packages/use-url-state/src/index.ts
  packages/use-url-state/tsconfig.json
  packages/use-url-state/webpack.config.js
Labels: feature
