Repository alibaba/hooks, pull requests merged in 2020-11, with the labels that each got.

#701 fix:useReactive添加缓存以及修改文档
  packages/hooks/src/useReactive/demo/demo3.tsx
  packages/hooks/src/useReactive/index.en-US.md
  packages/hooks/src/useReactive/index.ts
  packages/hooks/src/useReactive/index.zh-CN.md
Labels: enhancement

#704 docs: add Chinese docs for useTrackedEffect
  packages/hooks/src/useTrackedEffect/demo/demo1.tsx
  packages/hooks/src/useTrackedEffect/index.zh-CN.md
Labels: documentation

#703 feat: useLockFn
  .gitignore
  packages/hooks/src/index.ts
  packages/hooks/src/useLockFn/__tests__/index.test.ts
  packages/hooks/src/useLockFn/demo/demo1.tsx
  packages/hooks/src/useLockFn/index.en-US.md
  packages/hooks/src/useLockFn/index.ts
  packages/hooks/src/useLockFn/index.zh-CN.md
Labels: feature

#708 useInViewport 方法，增加区分未获取到dom元素时候的状态。
  packages/hooks/src/useInViewport/index.ts
Labels: enhancement

#712 feat: usePersistFn avoid calling useCallback (possible optimization)
  packages/hooks/src/usePersistFn/index.ts
Labels: enhancement

#744 optimize: useResponsive
  packages/hooks/src/useResponsive/index.ts
Labels: enhancement
